<div class="container">
    <div class="d-flex justify-content-center">
        <div class="col-md-5">
            <h3><?php echo $message?></h3>
            <form class="col-md-12" method="post" action="/newstock/user/login">
                <div class="form-group">
                    <label for="exampleDropdownFormEmail1">Email address</label>
                    <input name="email" type="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
                </div>
                <div class="form-group">
                    <label for="exampleDropdownFormPassword2">Password</label>
                    <input name="password" type="password" class="form-control" id="exampleDropdownFormPassword2" placeholder="Password">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="dropdownCheck">
                    <label class="form-check-label" for="dropdownCheck">
                        Remember me
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">Sign in</button>
            </form>
            <div class="dropdown-divider"></div>
            <a href="/newstock/user/sign">New around here? Sign up</a>
        </div>

    </div>
</div>
