<div class="container">
    <div class="d-flex justify-content-center">
        <div class="col-md-5">
            <h4><?php
                print_r($message);?></h4>
            <form class="col-md-12" action="/newstock/user/sign" method="post">
                <div class="form-group">
                    <label for="exampleDropdownFormEmail1">Email address</label>
                    <input type="email" name="email" class="form-control" id="exampleDropdownFormEmail1" placeholder="email@example.com">
                </div>
                <div class="form-group">
                    <label for="exampleDropdownFormPassword1">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleDropdownFormPassword1" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="exampleDropdownFormPassword2">Password Confirm</label>
                    <input type="password" name="passwordcon" class="form-control" id="exampleDropdownFormPassword2" placeholder="Password">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="dropdownCheck">
                    <label class="form-check-label" for="dropdownCheck">
                        Remember me
                    </label>
                </div>
                <button type="submit" name="btnsignin" class="btn btn-primary">Sign in</button>
            </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/newstock/user/login">Login</a>
        </div>

    </div>
</div>
